package diagnostic

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ChristopherAparicio/aisync/internal/session"
)

// fixGenerator is a function that produces artefacts for a specific problem.
type fixGenerator func(problem Problem, report *InspectReport, paths ProviderPaths, provider session.ProviderName) []Artefact

// registry maps problem IDs to their fix generators.
var registry = map[ProblemID]fixGenerator{
	ProblemExpensiveScreenshots: genFixExpensiveScreenshots,
	ProblemOversizedScreenshots: genFixOversizedScreenshots,
	ProblemUnresizedScreenshots: genFixUnresizedScreenshots,
	ProblemFrequentCompaction:   genFixFrequentCompaction,
	ProblemContextNearLimit:     genFixContextNearLimit,
	ProblemVerboseCommands:      genFixVerboseCommands,
	ProblemRepeatedCommands:     genFixRepeatedCommands,
	ProblemToolErrorLoops:       genFixToolErrorLoops,
	ProblemHighInputRatio:       genFixHighInputRatio,
	ProblemYoloEditing:          genFixYoloEditing,
	ProblemConversationDrift:    genFixConversationDrift,
	ProblemContextThrashing:     genFixContextThrashing,

	// RTK module
	ProblemRTKCurlConflict:    genFixRTKCurlConflict,
	ProblemRTKSecretRedaction: genFixRTKSecretRedaction,
	ProblemRTKIdenticalRetry:  genFixRTKIdenticalRetry,

	// API module
	ProblemAPIRetryLoop:          genFixAPIRetryLoop,
	ProblemIdenticalCommandBurst: genFixIdenticalCommandBurst,
}

// GenerateFixes produces provider-specific artefacts for all detected problems.
func GenerateFixes(report *InspectReport, provider session.ProviderName) *FixSet {
	paths := ProviderPathsFor(provider)

	fs := &FixSet{
		SessionID: report.SessionID,
		Provider:  string(provider),
	}

	for _, problem := range report.Problems {
		gen, ok := registry[problem.ID]
		if !ok {
			continue // no fix generator for this problem
		}
		artefacts := gen(problem, report, paths, provider)
		if len(artefacts) == 0 {
			continue
		}
		// Collect documentation links for the artefact kinds in this fix.
		docLinks := ProviderDocLinks(provider)
		seen := make(map[string]bool)
		for _, a := range artefacts {
			for _, dl := range ArtefactDocLinks(provider, a.Kind) {
				if !seen[dl.URL] {
					seen[dl.URL] = true
					docLinks = append(docLinks, dl)
				}
			}
		}
		// Dedup provider-level links that also appeared as artefact-level.
		var uniqueLinks []DocLink
		linkSet := make(map[string]bool)
		for _, dl := range docLinks {
			if !linkSet[dl.URL] {
				linkSet[dl.URL] = true
				uniqueLinks = append(uniqueLinks, dl)
			}
		}

		fs.Fixes = append(fs.Fixes, ProblemFix{
			ProblemID:    problem.ID,
			ProblemTitle: problem.Title,
			Severity:     problem.Severity,
			Artefacts:    artefacts,
			DocLinks:     uniqueLinks,
		})
	}

	return fs
}

// ── Image fix generators ────────────────────────────────────────────────────

func genFixExpensiveScreenshots(p Problem, r *InspectReport, paths ProviderPaths, provider session.ProviderName) []Artefact {
	var arts []Artefact

	// 1. Capture script
	arts = append(arts, genCaptureScript(paths, provider))

	// 2. Agent instructions patch
	patch := screenshotInstructionsPatch(r)
	arts = append(arts, Artefact{
		Kind:        ArtefactAgentInstructions,
		Description: "Screenshot protocol — describe-and-discard, resolution limits, JPEG preference",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	})

	// 3. Provider-specific skill/command
	arts = append(arts, genProviderSpecificScreenshot(paths, provider)...)

	return arts
}

func genFixOversizedScreenshots(p Problem, r *InspectReport, paths ProviderPaths, provider session.ProviderName) []Artefact {
	var arts []Artefact

	arts = append(arts, genCaptureScript(paths, provider))

	patch := fmt.Sprintf(`
## Screenshot Resolution (generated by aisync inspect)

Current screenshots are resized to 1000px. At ~1500 tokens per image with avg %.0f turns in context, this costs est. $%.2f.
Reducing to 500px max dimension and JPEG Q50 reduces tokens by ~66%%.

- Target: 500px max dimension, JPEG quality 50
- Use the capture-screen script instead of manual simctl+sips
`, r.Images.AvgTurnsInCtx, r.Images.EstImageCost)

	arts = append(arts, Artefact{
		Kind:        ArtefactAgentInstructions,
		Description: "Screenshot resolution reduction — 1000px to 500px",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	})

	return arts
}

func genFixUnresizedScreenshots(p Problem, r *InspectReport, paths ProviderPaths, provider session.ProviderName) []Artefact {
	var arts []Artefact

	arts = append(arts, genCaptureScript(paths, provider))

	unresized := r.Images.SimctlCaptures - r.Images.SipsResizes
	patch := fmt.Sprintf(`
## Screenshot Resize Required (generated by aisync inspect)

%d of %d screenshots were captured without resize. Raw retina screenshots are 3000-6000 tokens each.
Always resize before reading.

- ALWAYS resize screenshots before reading: sips -Z 500 <file> --out <resized>
- Use the capture-screen script for automatic resize + JPEG conversion
- Never read raw xcrun simctl screenshots directly
`, unresized, r.Images.SimctlCaptures)

	arts = append(arts, Artefact{
		Kind:        ArtefactAgentInstructions,
		Description: "Require screenshot resize before reading",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	})

	return arts
}

// genCaptureScript produces the optimized capture-screen.sh script.
func genCaptureScript(paths ProviderPaths, provider session.ProviderName) Artefact {
	scriptDir := paths.ScriptsDir
	if scriptDir == "" {
		scriptDir = "scripts/"
	}
	return Artefact{
		Kind:        ArtefactScript,
		Description: "Optimized screenshot capture — 500px max, JPEG Q50, ~66% token reduction",
		RelPath:     filepath.Join(scriptDir, "capture-screen.sh"),
		Content: `#!/bin/bash
# Generated by aisync inspect — optimized screenshot capture
# Reduces token cost by ~66% (1500 → ~500 tokens per image)
#
# Usage: ./capture-screen.sh [output-path]
# Default output: /tmp/screenshot.jpg

set -euo pipefail

DEVICE="${DEVICE_ID:-booted}"
OUT="${1:-/tmp/screenshot.jpg}"
RAW=$(mktemp /tmp/aisync-capture-XXXXXX.png)

# Capture
xcrun simctl io "$DEVICE" screenshot "$RAW" 2>/dev/null

# Resize to 500px max dimension
sips -Z 500 "$RAW" --out "$RAW" >/dev/null 2>&1

# Convert to JPEG Q50 for minimum token cost
sips -s format jpeg -s formatOptions 50 "$RAW" --out "$OUT" >/dev/null 2>&1

# Cleanup
rm -f "$RAW"

echo "$OUT"
`,
	}
}

// screenshotInstructionsPatch produces the agent instructions section for screenshot handling.
func screenshotInstructionsPatch(r *InspectReport) string {
	var sb strings.Builder
	sb.WriteString("\n## Screenshot Protocol (generated by aisync inspect)\n\n")

	if r.Images != nil && r.Images.EstImageCost > 0 {
		sb.WriteString(fmt.Sprintf("Session analysis: %d images, avg %.0f turns in context, est. cost $%.2f.\n\n",
			r.Images.ToolReadImages, r.Images.AvgTurnsInCtx, r.Images.EstImageCost))
	}

	sb.WriteString(`Rules:
- Use ./capture-screen.sh (or scripts/capture-screen.sh) instead of raw simctl + sips
- After reading a screenshot, describe what you see in 2-3 sentences of text
- Never re-read a screenshot you already described in the last 10 messages
- Prefer JPEG over PNG for all screenshots
- Target resolution: 500px max dimension (not 1000px)
- If a screenshot shows the expected result, say so and move on — do not re-capture
`)
	return sb.String()
}

// genProviderSpecificScreenshot generates skill/command artefacts specific to the provider.
func genProviderSpecificScreenshot(paths ProviderPaths, provider session.ProviderName) []Artefact {
	switch provider {
	case session.ProviderOpenCode:
		if paths.SkillsDir == "" {
			return nil
		}
		skillDir := filepath.Join(paths.SkillsDir, "screenshot-capture")
		return []Artefact{{
			Kind:        ArtefactSkill,
			Description: "OpenCode skill — screenshot capture with optimized settings",
			RelPath:     filepath.Join(skillDir, "SKILL.md"),
			Content: `# Screenshot Capture Skill

Capture iOS simulator screenshots optimized for token economy.

## Usage

Run the capture script:
` + "```bash\n./capture-screen.sh [output-path]\n```" + `

## Rules

- Always use this skill instead of raw ` + "`xcrun simctl io ... screenshot`" + `
- Output is JPEG at 500px max dimension (~500 tokens vs ~1500 for PNG at 1000px)
- After reading the screenshot, describe what you see — do not keep it in context
`,
		}}

	case session.ProviderClaudeCode:
		if paths.CommandsDir == "" {
			return nil
		}
		return []Artefact{{
			Kind:        ArtefactCommand,
			Description: "Claude Code command — capture and read simulator screenshot",
			RelPath:     filepath.Join(paths.CommandsDir, "capture-screenshot.md"),
			Content: `# Capture Screenshot

Capture an iOS simulator screenshot optimized for token economy.

Steps:
1. Run: ` + "`bash scripts/capture-screen.sh /tmp/screenshot.jpg`" + `
2. Read the resulting JPEG file
3. Describe what you see in 2-3 sentences
4. Do not re-read the same screenshot
`,
		}}

	default:
		return nil
	}
}

// ── Compaction fix generators ───────────────────────────────────────────────

func genFixFrequentCompaction(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	c := r.Compaction
	if c == nil {
		return nil
	}

	patch := fmt.Sprintf(`
## Context Management (generated by aisync inspect)

Session analysis: %d compactions, %.3f per user message, %s tokens lost.

Rules:
- When working on a long task, proactively summarize progress every 20-30 messages
- If a sub-task is complete, state the result concisely before starting the next one
- Avoid keeping large file contents in the conversation — read, extract what you need, move on
- When the conversation exceeds 100 messages, consider starting a new session with a handoff summary
`, c.Count, c.PerUserMsg, fmtInt(c.TotalTokensLost))

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Context management rules — reduce compaction frequency",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixContextNearLimit(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	c := r.Compaction
	if c == nil {
		return nil
	}

	patch := fmt.Sprintf(`
## Context Window Pressure (generated by aisync inspect)

Session analysis: avg context at compaction: %sK tokens. Context consistently near window limit.

Rules:
- Do not paste entire files into the conversation — use targeted reads with line ranges
- Summarize tool outputs instead of including raw output in responses
- For long test runs, pipe through tail -50 or head -50 to limit output
- Split multi-step tasks into separate sessions when context grows large
`, fmtK(c.AvgBeforeTokens))

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Context window pressure rules — avoid hitting the limit",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixContextThrashing(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	c := r.Compaction
	if c == nil {
		return nil
	}

	patch := fmt.Sprintf(`
## Context Thrashing Prevention (generated by aisync inspect)

Session analysis: %d compactions with median gap of %d messages. Context fills and compacts rapidly.

Rules:
- This session hit rapid fill/compact cycles — each cycle loses context and degrades quality
- Start new sessions for distinct tasks instead of continuing a single long session
- Keep file reads targeted: use line offsets and limits instead of reading entire files
- After a compaction, re-state the current goal and relevant context in 2-3 sentences
`, c.Count, c.IntervalMedian)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Context thrashing prevention — break rapid fill/compact cycles",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── Command fix generators ──────────────────────────────────────────────────

func genFixVerboseCommands(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	cmd := r.Commands
	if cmd == nil {
		return nil
	}

	var topCmdLines strings.Builder
	for _, c := range cmd.TopByOutput {
		if c.TotalBytes < 10_000 {
			break
		}
		topCmdLines.WriteString(fmt.Sprintf("- `%s`: %s total across %d calls\n",
			c.Command, fmtBytes(c.TotalBytes), c.Invocations))
	}

	patch := fmt.Sprintf(`
## Command Output Limits (generated by aisync inspect)

Session analysis: %s total command output across %d commands.

Top commands by output volume:
%s
Rules:
- Pipe verbose commands through tail -50 or head -50
- For test output: use --no-coverage and capture only failures
- For build output: redirect to a file and read only on failure
- Never run unbounded cat on files > 200 lines — use read with offset/limit
- For grep/search: limit results with -m 20 (max matches)
`, fmtBytes(cmd.TotalOutputBytes), cmd.TotalCommands, topCmdLines.String())

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Command output limits — reduce verbose tool output",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixRepeatedCommands(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	cmd := r.Commands
	if cmd == nil {
		return nil
	}

	duplicates := cmd.TotalCommands - cmd.UniqueCommands

	patch := fmt.Sprintf(`
## Command Repetition (generated by aisync inspect)

Session analysis: %d of %d commands (%.0f%%%%) were repeated.

Rules:
- Before re-running a command, check if the output from the last run is still in context
- Cache test results: if tests passed 5 messages ago and no code changed, do not re-run
- For status checks (git status, etc.), only run when state may have changed
- Group related changes and run tests once, not after each edit
`, duplicates, cmd.TotalCommands, cmd.RepeatedRatio*100)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Reduce command repetition — cache results, batch checks",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── Token fix generators ────────────────────────────────────────────────────

func genFixHighInputRatio(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	t := r.Tokens
	if t == nil {
		return nil
	}

	patch := fmt.Sprintf(`
## Token Economy (generated by aisync inspect)

Session analysis: input/output ratio %.0f:1 (%s input, %s output).
The model processes %.0f× more tokens than it generates.

Rules:
- High input ratio indicates the context is dominated by accumulated conversation history
- Split long tasks into focused sub-sessions of 50-80 messages each
- At session start, provide a concise summary of relevant context instead of relying on full history
- Remove boilerplate from tool outputs before continuing
`, t.InputOutputRatio, fmtTok(int64(t.Input)), fmtTok(int64(t.Output)), t.InputOutputRatio)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Token economy rules — reduce input/output ratio",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── Tool error fix generators ───────────────────────────────────────────────

func genFixToolErrorLoops(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	te := r.ToolErrors
	if te == nil {
		return nil
	}

	var loopLines strings.Builder
	for _, l := range te.ErrorLoops {
		loopLines.WriteString(fmt.Sprintf("- `%s`: %d consecutive errors (msgs %d-%d)\n",
			l.ToolName, l.ErrorCount, l.StartMsgIdx, l.EndMsgIdx))
	}

	patch := fmt.Sprintf(`
## Tool Error Handling (generated by aisync inspect)

Session analysis: %d error loops detected (3+ consecutive failures on same tool).

Observed loops:
%s
Rules:
- After 2 consecutive failures on the same tool, stop and analyze the error before retrying
- If a bash command fails, read the error output completely before attempting a fix
- If a file edit fails (oldString not found), re-read the file to see current content
- Never retry the exact same command more than 3 times — change approach after 2 failures
- For test failures: read the full error, identify root cause, fix, then re-run once
`, len(te.ErrorLoops), loopLines.String())

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Tool error handling — break retry loops",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── Behavioral pattern fix generators ───────────────────────────────────────

func genFixYoloEditing(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	pat := r.Patterns
	if pat == nil {
		return nil
	}

	patch := fmt.Sprintf(`
## File Editing Protocol (generated by aisync inspect)

Session analysis: %d files were edited without being read first.

Rules:
- ALWAYS read a file (or the relevant section) before editing it
- For large files, read at least the section around the target edit location
- Never write an entire file from memory — read first, then edit with precise oldString/newString
- If an edit fails, re-read the file to see current content before retrying
`, pat.WriteWithoutReadCount)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "File editing protocol — read before edit",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixConversationDrift(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	pat := r.Patterns
	if pat == nil {
		return nil
	}

	var observations []string
	if pat.UserCorrectionCount >= 5 {
		observations = append(observations, fmt.Sprintf("%d user corrections", pat.UserCorrectionCount))
	}
	if pat.LongestRunLength >= 30 {
		observations = append(observations, fmt.Sprintf("longest unguided run: %d messages", pat.LongestRunLength))
	}

	patch := fmt.Sprintf(`
## Conversation Focus (generated by aisync inspect)

Session analysis: %s.

Rules:
- After every 10-15 tool calls, briefly state what you accomplished and what remains
- If the user corrects you, acknowledge the correction and re-state the updated goal
- Do not explore tangential issues unless explicitly asked
- For long implementation tasks, outline the plan first, then execute step by step
- If unsure about approach, ask the user rather than exploring multiple paths
`, strings.Join(observations, ", "))

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Conversation focus — reduce drift and corrections",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── RTK fix generators ──────────────────────────────────────────────────────

func genFixRTKCurlConflict(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	curlVia := 0
	if stats := GetRTKStats(r); stats != nil {
		curlVia = stats.CurlViaRTK
	}

	patch := fmt.Sprintf(`
## RTK + curl Exclusion (generated by aisync inspect)

Session analysis: %d curl calls routed through RTK. RTK compresses JSON responses
to schema-only output, hiding actual error messages and values.

Rules:
- NEVER run curl through RTK — always use /usr/bin/curl or plain curl
- RTK is for build/test commands only (go test, npm test, pytest, etc.)
- For API debugging: use curl directly and pipe through jq for formatting
- If you need to save API responses, redirect output to a file: curl ... > /tmp/response.json
`, curlVia)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "RTK + curl exclusion — never proxy HTTP clients through RTK",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixRTKSecretRedaction(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	redacted := 0
	if stats := GetRTKStats(r); stats != nil {
		redacted = stats.RedactedOutputs
	}

	patch := fmt.Sprintf(`
## RTK Secret Redaction Awareness (generated by aisync inspect)

Session analysis: %d command outputs contained RTK redaction markers.
RTK replaces JWT tokens and API keys with ***REDACTED*** placeholders.

Rules:
- For authentication flows, bypass RTK entirely — use /usr/bin/curl
- If output contains ***REDACTED***, the actual values have been removed by RTK
- Do not attempt to parse or use REDACTED values — re-run without RTK
- For commands that need to see secrets (login, token exchange), never use rtk prefix
`, redacted)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "RTK secret redaction awareness — bypass for auth flows",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixRTKIdenticalRetry(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	burstCount := 0
	if stats := GetRTKStats(r); stats != nil {
		burstCount = len(stats.RetryBursts)
	}

	patch := fmt.Sprintf(`
## RTK Retry Prevention (generated by aisync inspect)

Session analysis: %d burst clusters of identical RTK commands detected.
RTK's output compression prevents diagnosis of the underlying failure.

Rules:
- After 2 identical rtk command failures, drop RTK and re-run the raw command
- If rtk output shows only type signatures (e.g. {code: string}), re-run without rtk to see actual values
- Never retry the same rtk command more than 2 times — switch to the raw command
- For debugging: raw command first, add rtk back only after the command succeeds
`, burstCount)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "RTK retry prevention — drop RTK after 2 failures",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

// ── API fix generators ──────────────────────────────────────────────────────

func genFixAPIRetryLoop(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	var endpointLines strings.Builder
	if stats := GetAPIStats(r); stats != nil {
		for _, ep := range stats.EndpointCalls {
			if ep.Count >= 5 {
				endpointLines.WriteString(fmt.Sprintf("- %s: called %d times\n", ep.URL, ep.Count))
			}
		}
	}

	patch := fmt.Sprintf(`
## API Retry Limits (generated by aisync inspect)

Session analysis — heavily retried endpoints:
%s
Rules:
- After 2 failed API calls to the same endpoint, stop and analyze the response body
- Read the full error response before retrying — do not retry on the same error
- If authentication fails twice, check credentials/token before retrying the endpoint
- Save API responses to /tmp/*.json for inspection: curl ... > /tmp/response.json && cat /tmp/response.json
- Maximum 3 calls to the same endpoint without changing the request
`, endpointLines.String())

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "API retry limits — analyze errors before retrying",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}

func genFixIdenticalCommandBurst(p Problem, r *InspectReport, paths ProviderPaths, _ session.ProviderName) []Artefact {
	burstCount := 0
	if stats := GetAPIStats(r); stats != nil {
		burstCount = len(stats.CommandBursts)
	}

	patch := fmt.Sprintf(`
## Command Burst Prevention (generated by aisync inspect)

Session analysis: %d burst clusters of identical commands detected.

Rules:
- Never run the exact same command 3+ times in a row
- After 2 identical failures, change approach: modify parameters, check prerequisites, or ask the user
- If a command produces no useful output, do not retry — investigate the environment
- For API calls: vary the request (different headers, payload, endpoint) before retrying
`, burstCount)

	return []Artefact{{
		Kind:        ArtefactAgentInstructions,
		Description: "Command burst prevention — change approach after 2 identical failures",
		RelPath:     paths.InstructionsFile,
		Content:     patch,
		AppendTo:    true,
	}}
}
