// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: internal/secrets/scanplugin/proto/scanner.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *ScanRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*SecretMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *ScanResponse) GetMatches() []*SecretMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

type MaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskRequest) Reset() {
	*x = MaskRequest{}
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskRequest) ProtoMessage() {}

func (x *MaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskRequest.ProtoReflect.Descriptor instead.
func (*MaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *MaskRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type MaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaskedContent string                 `protobuf:"bytes,1,opt,name=masked_content,json=maskedContent,proto3" json:"masked_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaskResponse) Reset() {
	*x = MaskResponse{}
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaskResponse) ProtoMessage() {}

func (x *MaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaskResponse.ProtoReflect.Descriptor instead.
func (*MaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *MaskResponse) GetMaskedContent() string {
	if x != nil {
		return x.MaskedContent
	}
	return ""
}

type SecretMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	StartPos      int32                  `protobuf:"varint,3,opt,name=start_pos,json=startPos,proto3" json:"start_pos,omitempty"`
	EndPos        int32                  `protobuf:"varint,4,opt,name=end_pos,json=endPos,proto3" json:"end_pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMatch) Reset() {
	*x = SecretMatch{}
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMatch) ProtoMessage() {}

func (x *SecretMatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMatch.ProtoReflect.Descriptor instead.
func (*SecretMatch) Descriptor() ([]byte, []int) {
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *SecretMatch) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SecretMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretMatch) GetStartPos() int32 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *SecretMatch) GetEndPos() int32 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

var File_internal_secrets_scanplugin_proto_scanner_proto protoreflect.FileDescriptor

const file_internal_secrets_scanplugin_proto_scanner_proto_rawDesc = "" +
	"\n" +
	"/internal/secrets/scanplugin/proto/scanner.proto\x12\x0eaisync.secrets\"'\n" +
	"\vScanRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"E\n" +
	"\fScanResponse\x125\n" +
	"\amatches\x18\x01 \x03(\v2\x1b.aisync.secrets.SecretMatchR\amatches\"'\n" +
	"\vMaskRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"5\n" +
	"\fMaskResponse\x12%\n" +
	"\x0emasked_content\x18\x01 \x01(\tR\rmaskedContent\"m\n" +
	"\vSecretMatch\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1b\n" +
	"\tstart_pos\x18\x03 \x01(\x05R\bstartPos\x12\x17\n" +
	"\aend_pos\x18\x04 \x01(\x05R\x06endPos2\x95\x01\n" +
	"\rSecretScanner\x12A\n" +
	"\x04Scan\x12\x1b.aisync.secrets.ScanRequest\x1a\x1c.aisync.secrets.ScanResponse\x12A\n" +
	"\x04Mask\x12\x1b.aisync.secrets.MaskRequest\x1a\x1c.aisync.secrets.MaskResponseBIZGgithub.com/ChristopherAparicio/aisync/internal/secrets/scanplugin/protob\x06proto3"

var (
	file_internal_secrets_scanplugin_proto_scanner_proto_rawDescOnce sync.Once
	file_internal_secrets_scanplugin_proto_scanner_proto_rawDescData []byte
)

func file_internal_secrets_scanplugin_proto_scanner_proto_rawDescGZIP() []byte {
	file_internal_secrets_scanplugin_proto_scanner_proto_rawDescOnce.Do(func() {
		file_internal_secrets_scanplugin_proto_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_secrets_scanplugin_proto_scanner_proto_rawDesc), len(file_internal_secrets_scanplugin_proto_scanner_proto_rawDesc)))
	})
	return file_internal_secrets_scanplugin_proto_scanner_proto_rawDescData
}

var file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_secrets_scanplugin_proto_scanner_proto_goTypes = []any{
	(*ScanRequest)(nil),  // 0: aisync.secrets.ScanRequest
	(*ScanResponse)(nil), // 1: aisync.secrets.ScanResponse
	(*MaskRequest)(nil),  // 2: aisync.secrets.MaskRequest
	(*MaskResponse)(nil), // 3: aisync.secrets.MaskResponse
	(*SecretMatch)(nil),  // 4: aisync.secrets.SecretMatch
}
var file_internal_secrets_scanplugin_proto_scanner_proto_depIdxs = []int32{
	4, // 0: aisync.secrets.ScanResponse.matches:type_name -> aisync.secrets.SecretMatch
	0, // 1: aisync.secrets.SecretScanner.Scan:input_type -> aisync.secrets.ScanRequest
	2, // 2: aisync.secrets.SecretScanner.Mask:input_type -> aisync.secrets.MaskRequest
	1, // 3: aisync.secrets.SecretScanner.Scan:output_type -> aisync.secrets.ScanResponse
	3, // 4: aisync.secrets.SecretScanner.Mask:output_type -> aisync.secrets.MaskResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_secrets_scanplugin_proto_scanner_proto_init() }
func file_internal_secrets_scanplugin_proto_scanner_proto_init() {
	if File_internal_secrets_scanplugin_proto_scanner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_secrets_scanplugin_proto_scanner_proto_rawDesc), len(file_internal_secrets_scanplugin_proto_scanner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_secrets_scanplugin_proto_scanner_proto_goTypes,
		DependencyIndexes: file_internal_secrets_scanplugin_proto_scanner_proto_depIdxs,
		MessageInfos:      file_internal_secrets_scanplugin_proto_scanner_proto_msgTypes,
	}.Build()
	File_internal_secrets_scanplugin_proto_scanner_proto = out.File
	file_internal_secrets_scanplugin_proto_scanner_proto_goTypes = nil
	file_internal_secrets_scanplugin_proto_scanner_proto_depIdxs = nil
}
