// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: internal/secrets/scanplugin/proto/scanner.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretScanner_Scan_FullMethodName = "/aisync.secrets.SecretScanner/Scan"
	SecretScanner_Mask_FullMethodName = "/aisync.secrets.SecretScanner/Mask"
)

// SecretScannerClient is the client API for SecretScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretScanner is the gRPC service that external plugins implement.
type SecretScannerClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error)
}

type secretScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretScannerClient(cc grpc.ClientConnInterface) SecretScannerClient {
	return &secretScannerClient{cc}
}

func (c *secretScannerClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, SecretScanner_Scan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secretScannerClient) Mask(ctx context.Context, in *MaskRequest, opts ...grpc.CallOption) (*MaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaskResponse)
	err := c.cc.Invoke(ctx, SecretScanner_Mask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretScannerServer is the server API for SecretScanner service.
// All implementations must embed UnimplementedSecretScannerServer
// for forward compatibility.
//
// SecretScanner is the gRPC service that external plugins implement.
type SecretScannerServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	Mask(context.Context, *MaskRequest) (*MaskResponse, error)
	mustEmbedUnimplementedSecretScannerServer()
}

// UnimplementedSecretScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretScannerServer struct{}

func (UnimplementedSecretScannerServer) Scan(context.Context, *ScanRequest) (*ScanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedSecretScannerServer) Mask(context.Context, *MaskRequest) (*MaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mask not implemented")
}
func (UnimplementedSecretScannerServer) mustEmbedUnimplementedSecretScannerServer() {}
func (UnimplementedSecretScannerServer) testEmbeddedByValue()                       {}

// UnsafeSecretScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretScannerServer will
// result in compilation errors.
type UnsafeSecretScannerServer interface {
	mustEmbedUnimplementedSecretScannerServer()
}

func RegisterSecretScannerServer(s grpc.ServiceRegistrar, srv SecretScannerServer) {
	// If the following call panics, it indicates UnimplementedSecretScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretScanner_ServiceDesc, srv)
}

func _SecretScanner_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretScannerServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretScanner_Scan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretScannerServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecretScanner_Mask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretScannerServer).Mask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretScanner_Mask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretScannerServer).Mask(ctx, req.(*MaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretScanner_ServiceDesc is the grpc.ServiceDesc for SecretScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aisync.secrets.SecretScanner",
	HandlerType: (*SecretScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _SecretScanner_Scan_Handler,
		},
		{
			MethodName: "Mask",
			Handler:    _SecretScanner_Mask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/secrets/scanplugin/proto/scanner.proto",
}
